scale: 1
metatile: 1
name: "Undercoat"
bounds:
  - 0.2636
  - 47.606
  - 4.878
  - 49.8026
center:
  - 2.3427
  - 48.8662
  - 14
format: "png"
interactivity: false
minzoom: 9
maxzoom: 15
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
Stylesheet:
- base.mss
- labels.mss
source: 'tms://localhost:3579/all/{z}/{x}/{y}.mvt'
# source: 'tms://carto.data.gouv.fr/vector/all/{z}/{x}/{y}.mvt'
layers:
  - landuse
  - boundaries
  - waterarea
  - railways
  - roads.geo
  - places
  - roads.label
