scale: 1
metatile: 4
name: "Undercoat"
bounds:
  - 0.2636
  - 47.606
  - 4.878
  - 49.8026
center:
  - 2.3427
  - 48.8662
  - 14
format: "png"
interactivity: false
minzoom: 9
maxzoom: 15
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
Stylesheet:
- base.mss
- labels.mss
Layer:
- id: land
  name: "land"
  class: ""
  geometry: "polygon"
  extent:
    - -180
    - -85.05112877980659
    - 180
    - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    file: "http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip"
    type: "shape"
  advanced: {}
- id: landuse
  name: "landuse"
  class: ""
  geometry: "polygon"
  extent:
    - -180
    - -85.05112877980659
    - 180
    - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
      ( SELECT
          geometry, type
        FROM
          osm_landusages
        WHERE
          type IS NOT NULL
        ORDER BY
          area DESC
      ) AS data
- id: landuse_gen
  name: landuse_gen
  class: ""
  geometry: "polygon"
  extent:
    - -180
    - -85.05112877980659
    - 180
    - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
      ( SELECT
          geometry, type
        FROM
          osm_landusages_gen
        WHERE
          type IN ('park', 'garden', 'forest', 'wood', 'cemetery', 'grass')
      ) AS data
- id: waterway
  name: waterway
  class: ""
  geometry: polygon
  extent:
    - -180
    - -85.05112877980659
    - 180
    - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
      ( SELECT
          geometry, type, area
        FROM
          osm_waterareas
      ) AS data
- id: buildings
  name: buildings
  class: ""
  geometry: polygon
  extent:
    - -180
    - -85.05112877980659
    - 180
    - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
      ( SELECT
          geometry, type
        FROM
          osm_buildings
      ) AS data
- id: roads_gen
  name: roads_gen
  class: ""
  geometry: linestring
  extent:
    - -180
    - -85.05112877980659
    - 180
    - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
      ( SELECT
          geometry, type, ref
        FROM
          osm_roads_gen
        WHERE
          type IN ('motorway', 'trunk', 'primary', 'secondary', 'primary_link', 'motorway_link', 'trunk_link')
      ) AS data
- id: boundary
  name: boundary
  class: ""
  geometry: polygon
  extent:
  - -180
  - -85.05112877980659
  - 180
  - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
        ( SELECT
            geometry, admin_level
          FROM
            osm_admin
          WHERE
            "type"='administrative'
            AND admin_level IN (4,6,8,9)
            AND "type" IS NOT NULL
          ORDER BY
            admin_level DESC
        ) AS data
- id: railway
  name: railway
  class: ""
  geometry: linestring
  extent:
    - -180
    - -85.05112877980659
    - 180
    - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
      ( SELECT
          geometry, type, name, tunnel, bridge, ref, access, service, class
        FROM
          osm_railway
        WHERE
          service != 'spur' AND type NOT IN ('funicular', 'disused', 'tram', 'monorail')
        ORDER BY
          z_order
      ) AS data
- id: roads
  name: roads
  class: ""
  geometry: linestring
  extent:
    - -180
    - -85.05112877980659
    - 180
    - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
      ( SELECT
          geometry, type, ref
        FROM
          osm_roads
        WHERE
          type NOT IN ('path', 'footway', 'stairs')
      ) AS data
- id: place
  name: place
  class: ""
  geometry: point
  extent:
  - -180
  - -85.05112877980659
  - 180
  - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
        ( SELECT
            geometry,
            CASE WHEN type='city' THEN 1 WHEN type='town' THEN 2 ELSE 100 END as prio,
            type, name, z_order, population
          FROM
            osm_places
          WHERE
            type IN ('city', 'town', 'village')
            AND type IS NOT NULL
          ORDER BY prio, population DESC NULLS LAST
        ) AS data
- id: road_label
  name: road_label
  class: ""
  geometry: point
  extent:
  - -180
  - -85.05112877980659
  - 180
  - 85.05112877980659
  srs-name: "900913"
  srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
  Datasource:
    dbname: idf
    geometry_field: geometry
    type: postgis
    extent: -20037508,-19929239,20037508,19929239
    table: |-
        ( SELECT
            geometry, type, name, ref, CHAR_LENGTH(ref) AS reflen
          FROM
            osm_roads
          WHERE
            type IS NOT NULL AND name IS NOT NULL AND geometry && !bbox!
          ORDER BY
            z_order
        ) AS data
